# Generated by Django 6.0.1 on 2026-01-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='filmes/'),
        ),
    ]
